### ISSUE TITLE
Add support for AWS console access

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport-agent-terraform#1]
This module should have a flag to enable the AWS console support via Teleport Application Access. When set to enabled, the module should automatically provision the AWS console app with the correct account IDs.

**Comment by wadells** [comment]
Closing this out -- any future issues should be opened against teleport as we'll be maintaining the copy of this code in:

https://github.com/gravitational/teleport/tree/master/examples/aws/terraform
